set(HEADER_FILES 
    Eigen.h
    FreeImageHelper.h
    BFM.h
    FacialLandmarkDetection.h
    Renderer.h
    DenseOptimizer.h
)
set(SOURCE_FILES 
    FreeImageHelper.cpp
    Renderer.cpp
    DenseOptimizer.cpp
)